services:
  etl_anime_database:
    image: postgres:latest
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  etl_anime:
    build: .
    image: etl_anime
    environment:
      DATABASE_HOST: host.docker.internal
      DATBASE_USER: user
      DATABASE_PASSWORD: password
    depends_on:
      - etl_anime_database
