services:
  etl-anime-database:
    image: postgres:latest
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  etl-anime:
    build: .
    image: etl-anime
    depends_on:
      - etl-anime-database
