services:
  source_database_service:
    image: postgres:15.6
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - etl_network
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  destination_database_service:
    image: postgres:15.6
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - etl_network

  etl_script_service:
    build: ./scripts
    depends_on:
      - source_database_service
      - destination_database_service
    networks:
      - etl_network

#  dbt_service:
#    image: ghcr.io/dbt-labs/dbt-postgres:15.6
#    command: [ "run" ]
#    depends_on:
#      - etl_script_service
#    environment:
#      DBT_PROFILE: default
#      DBT_TARGET: dev
#    networks:
#      - etl_network
#    volumes:
#      - ./series_analytics
#      - ~/.dbt:/root

networks:
  etl_network:
    driver: bridge