
version: 2

sources:
  - name: database
    description: "Data from anime table"
    database: database
    schema: public
    tables:
      - name: anime
        description: "A list of anime series"
